server:
  port: 8771

# 如果路由方式是serviceId的方式，那么ribbon的生效，如果是url的方式，则zuul.host开头的生效
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 10000

spring:
  application:
    name: smart-cms-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
#        namespace: ${config.register.namespace} # 命名空间
        server-addr: http://localhost:8848/ # 配置nacos注册中心
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: smart-auth
          # lb代表从注册中心获取服务，且已负载均衡方式转发
          uri: lb://smart-cms-auth
          predicates:
            - Path=/smart-auth/**
          # 加上StripPrefix=1，否则转发到后端服务时会带上consumer前缀
          filters:
            - StripPrefix=1
        - id: smart-system
          # lb代表从注册中心获取服务，且已负载均衡方式转发
          uri: lb://smart-cms-base-system
          predicates:
            - Path=/smart-system/**
          # 加上StripPrefix=1，否则转发到后端服务时会带上consumer前缀
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8999/oauth/public-key' # 获取公钥
  redis:
    host: localhost
    port: 6379
    database: 8
    timeout: 1500
    jedis:
      pool:
        maxIdle: 999
        minIdle: 20

# 白名单(忽略鉴权)配置
security:
  ignoreUrls:
    # 登录接口
    - /smart-auth/oauth/**
    # Knife4j
    - /webjars/**
    - /doc.html
    - /swagger-resources/**
    - /*/v2/api-docs
    # 系统服务
    - /smart-system/api/**

# 以下配置避免nacos疯狂打印日志
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: warn