server:
  port: 8988

spring:
  application:
      name: smart-cms-product
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/ # 配置nacos注册中心
# 日志
logging:
  level:
    org:
      springframework:
        security: DEBUG