server:
  port: 8989

spring:
  application:
      name: smart-cms-system
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/ # 配置nacos注册中心
  redis:
    host: localhost
    port: 6379
    database: 8
    timeout: 1500
    jedis:
      pool:
        maxIdle: 999
        minIdle: 20
# 日志
logging:
  level:
    org:
      springframework:
        security: DEBUG