server:
  port: 8989

spring:
  application:
      name: smart-cms-base-system
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/ # 配置nacos注册中心
  redis:
    host: localhost
    port: 6379
    database: 8
    timeout: 1500
    jedis:
      pool:
        maxIdle: 999
        minIdle: 20
# 日志
logging:
  level:
    org:
      springframework:
        security: DEBUG

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50