server:
  port: 8999

spring:
  application:
    name: smart-cms-auth
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/ # 配置nacos注册中心
  jpa: #JPA配置
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: "*"
auth:
  token:
    alias: jwt
    jwtFileName: jwt.jks
    jwtPassword: yuntuo18419
  white-list:
    - "/rsa/publicKey" # 获取公钥
    - "/v2/api-docs" # swagger api json
    - "/swagger-resources/configuration/ui" # 用来获取支持的动作
    - "/swagger-resources" # 用来获取api-docs的URL
    - "/swagger-resources/configuration/security" # 安全选择
    - "/swagger-ui/**" # swagger3.0，访问地址是/swagger-ui/index.html
# 日志
logging:
  level:
    org:
      springframework:
        security: DEBUG