server:
  port: 8999

spring:
  application:
      name: smart-cms-auth
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/ # 配置nacos注册中心
  jpa: #JPA配置
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: "*"
auth:
  token:
    alias: jwt
    jwtFileName: jwt.jks
    jwtPassword: yuntuo18419
  white-list:
    - "/rsa/publicKey" # 获取公钥
# 日志
logging:
  level:
    org:
      springframework:
        security: DEBUG